# Generated by Django 4.1.4 on 2022-12-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Triangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("edge1", models.FloatField()),
                ("edge2", models.FloatField()),
                ("edge3", models.FloatField()),
            ],
            options={
                "db_table": "triangles",
            },
        ),
    ]
